### ISSUE TITLE
日常优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#101]
https://docs.qq.com/desktop/mydoc/folder/JpzDOTDbypxe

<img width="394" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/ba0f124f-9150-4b08-a60f-5c1010d9acc6">

+ 增加首页位置
+ 增加pvx中的 https://www.jx3box.com/pvg/gonggao/daily （参考设计稿）

- [x] 已完成

**Comment by iRuxu** [comment]
## 简要说明
<img width="457" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/85a61655-22bf-4b47-a673-be659eb55ebe">


- [x] 已完成

**Comment by iRuxu** [comment]
## 后台
<img width="449" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/3288d4f8-aa20-4932-8591-29d65c8093e1">

- [x] 已完成

**Comment by iRuxu** [comment]
## 日常

+ 秘境日常：每天
+ 声望日常：每天
+ 战场日常：每天
+ 五人周常：每周
+ 十人周常：每周

以上由插件上报，然后人工查阅修订
阵营日常废弃掉，没必要，是固定1个

- [x] 已完成

**Comment by iRuxu** [comment]
## 世界首领

不做上报，由人工每周一和每周四进行更新
![5f77f71790908023e1ceb747a2e8b74a_720](https://github.com/JX3BOX/MY/assets/8476969/b0d08607-e066-45a8-9117-af8e88eeccb6)

仅正式服有这个，怀旧服没有

- [x] 已完成

**Comment by iRuxu** [comment]
## 活动（节日/特殊）

人工维护，双端都有

- [x] 已完成

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/index/assets/30660189/67472893-6eb2-4774-9998-dd5b1a4707b0)
