### ISSUE TITLE
其它

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#111]
## index
![0c7c12fc0c843aacc10da004faa0ae60](https://github.com/JX3BOX/index/assets/8476969/609d0045-25b5-4538-bc33-91308e20be03)

奇怪，要挪上去

- [x] 已完成

**Comment by iRuxu** [comment]
## os
用户管理
<img width="1919" alt="image" src="https://github.com/JX3BOX/os/assets/8476969/c7490af6-d73d-4c4f-a682-f441a0bc0499">


<img width="821" alt="image" src="https://github.com/JX3BOX/os/assets/8476969/677128cd-6ec1-44a5-b402-6e97800f9c8c">

线上样式有问题

- [x] 已完成

**Comment by fifthThirteen** [comment]
// 备注用户
/api/cms/manage/user/remark/${userId}

获取用户备注 为null
