### ISSUE TITLE
魔盒features

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#119]
## 入口

<img width="354" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/ea2b3bb2-7dd4-4803-91b6-54dcb0f7bb90">

这个地方是通过后台 https://www.jx3box.com/os/#/dev/navigation/panel 这里实现的，扩展一下这里

（1）让其支持图标
（2）让其支持一个附属的值（具体的值就是后台编辑的，比如就叫meta）

- [x] 已完成

**Comment by iRuxu** [comment]
## 新增项

新增一个非管理的项。

叫魔盒features 【功能更新】

然后点击链接会跳到对应的链接，初步定  /index/features

- [x] 已完成

**Comment by iRuxu** [comment]
## 逻辑

比如我们最近新有个什么功能，我们就把这个meta值设为 20240619 
你记录到Localstorage

如果下次我们又更新了一个功能，我们改这里的值。
如果和localstorage不一样，或者localstorage没有的时候。
那么那个更多的按钮也显示蓝色pop

<img width="329" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/9445d5af-e5c0-4e7a-98a9-ea597e5dfc80">

同时功能更新后面显示一个绿色的label  【new】
样式
<img width="115" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/b6a59d0f-ba68-4aa3-84aa-90d36cb583cf">

- [x] 已完成

**Comment by iRuxu** [comment]
## 首页更新

<img width="1105" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/9de40c59-b9bf-4359-acfa-1ddbcae03c55">

把这里增加一个路由参数。

让那个链接重定向到这里来先。

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## 首页更新
> <img alt="image" width="1105" src="https://private-user-images.githubusercontent.com/8476969/341101082-9de40c59-b9bf-4359-acfa-1ddbcae03c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzk1NjksIm5iZiI6MTcxOTEzOTI2OSwicGF0aCI6Ii84NDc2OTY5LzM0MTEwMTA4Mi05ZGU0MGM1OS1iOWJmLTQzNTktYWNmYS0xZGRiY2FlMDNjNTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjNUMTA0MTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU1YzE3NzY3MDg5OWQxMDg3MDhhMDJlZWFiOWEzYjk5Njk2MTUzNGE4ZGM2ZWEyNjQ4YTY1YTM1YTZmNDMyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TO2bOnlezGtEeCokXkE7bLRwaydJnty4fUr-xK5pEE4">
> 把这里增加一个路由参数。
> 
> 让那个链接重定向到这里来先。
> 
> * [x]  已完成

我暂时先直接把链接改成/notice?tab=feature
