### ISSUE TITLE
江湖战报优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#128]
<img width="1592" alt="image" src="https://github.com/user-attachments/assets/f1e22571-e63a-44c1-8161-b814e27eb7de">

把中间那一坨搬到右侧去，固定宽度。
中间flex:1

百战要设计给个图到时候，
底部2个按钮，1个叫”快速预览“，点击弹窗查看现在首页的这个块
另一个叫 ”查看详情“，新窗跳转到 https://www.jx3box.com/fb/baizhan

---
banner图要替换，只提交了没部署，包括新的名望
- [x] 已完成

**Comment by fifthThirteen** [comment]
pvg 活动告示新增披风会名望


- [x] 已完成
