### ISSUE TITLE
首页矩阵图标更换

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#131]
## 首页

pc首页的icon换掉
旧的整个放一个备份文件夹

图标向冰块要

![842a912da1de87f92ecc4851139850a6_720](https://github.com/user-attachments/assets/74e22c03-7ed5-466f-a33e-8ec3e49c3e50)

- [x] 醉栩：已完成

**Comment by iRuxu** [comment]
## Tool
更多页面也要换
https://www.jx3box.com/app/

- [x] 已完成

**Comment by iRuxu** [comment]
## 栏目

后续其它栏目本地逐步也更换
大部分会直接调用和矩阵一样的位置，少量在本地

- [x] 已了解

**Comment by iRuxu** [comment]
## 图片路径

回复在这里，方便小程序引用cdn地址

- [ ] 已完成

**Comment by iRuxu** [comment]
## 图标步骤

1. 新建一个 logo的库 ✔
2. 新建一个文件夹，叫  logo，把默认图标扔进去 ✔
3. 分别新建一个文件夹，叫 logo-light、logo-dark、logo-golden，用来放对应图标的指定主题色的 ✔
4. 新建一个脚本，这个脚本是用来处理这些图片的，跑一次的时候，批量把logo里的图标，按照规则处理到其他3个文件夹，主要就是替换对应类的颜色。这个类的颜色，最好在项目里有个theme.json在根目录来固定记录这个规则。✔
5. 新增一个app.json在根目录，是一个对象，里面包括  pve,pvp,pvx,common  到时候我来编写 ✔
6. 新增workflow，每次更新的时候，要对应传到oss的根目录去；主要使用cdn地址来引用这些图标 ✔
7. 另外放一份到南京2的img目录下，也可以通过img.jx3box.com/logo来访问，需要去改nginx的配置 ✔
8. 修改首页矩阵先 ✔
9. 修改tool的app页面 ✔
10. 最后检查各个栏目的引用，都要换

**Comment by iRuxu** [comment]
## rx后台

<img width="1917" alt="image" src="https://github.com/user-attachments/assets/ca569b15-6012-4a06-a764-8fc38666a8b3">

但我已经换成$os了

<img width="476" alt="image" src="https://github.com/user-attachments/assets/10021810-b258-4b77-becb-6851bf1f1f4b">

- [ ] 已完成

**Comment by iRuxu** [comment]
## 魔盒公告

<img width="1872" alt="image" src="https://github.com/user-attachments/assets/c4fa3b22-b780-4d53-aaa0-f1b57174ca5e">

https://www.jx3box.com/notice/?tab=feature

在index库

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## rx后台
> <img alt="image" width="1917" src="https://private-user-images.githubusercontent.com/8476969/388252521-ca569b15-6012-4a06-a764-8fc38666a8b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjA4NTEsIm5iZiI6MTczMjE2MDU1MSwicGF0aCI6Ii84NDc2OTY5LzM4ODI1MjUyMS1jYTU2OWIxNS02MDEyLTRhMDYtYTc2NC04ZmMzODY2NmE4YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDM0MjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMyNDc5MGMxYTY4Y2Q4MDY2Y2E4NGRkYmJkODIyY2E0YzI4MzFmMDJmZTA4YzQ1NzkyZWE1ZDI1ZGZjN2ZmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.08iVjxwtemrd-Cs6ZgxeQIDFVjge8OmiUt_R_dkbvU4">
> 
> 但我已经换成$os了
> <img alt="image" width="476" src="https://private-user-images.githubusercontent.com/8476969/388252705-10021810-b258-4b77-becb-6851bf1f1f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjA4NTEsIm5iZiI6MTczMjE2MDU1MSwicGF0aCI6Ii84NDc2OTY5LzM4ODI1MjcwNS0xMDAyMTgxMC1iMjU4LTRiNzctYmVjYi02ODUxYmYxZjFmNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDM0MjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDlkZDNkYjY0MzUwMTJiMzQyMGU4ZGFlMjU2NzhlZDYwM2JhNmQ2NGQxNjQ3ZGFmZGVhZWE1NTFhNDU4YjM5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zFLgW8KYxvr5VEtcmO5mBniVhO7f4HC-jNJZb41VE0Y">
> 
>     * [ ]  已完成

我这边是正常的，你是不是没有拉代码
![图片](https://github.com/user-attachments/assets/8a0ab3ef-a640-489e-887a-11c2c25b3873)

**Comment by iRuxu** [comment]
app.json 修改
同时app页面请使用app.json https://www.jx3box.com/app/

看下群里，持续跟进下，跟进到把图标全部补齐


- [x] 已完成

**Comment by iRuxu** [comment]
<img width="821" alt="image" src="https://github.com/user-attachments/assets/557452d9-4f8d-4c9d-8249-169890e1f1e1">
逐步把已经完工图标的栏目替换好，自己做好记录

- [ ] 已完成

**Comment by Kaviilee** [comment]
### 已替换
maro,bps,fb,pvp,tool,bbs部分,wiki,pz,dbm,team

### 未替换
pvx,publish,dashboard,author,vip
