### ISSUE TITLE
新版首页

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#22]
## 设计稿
https://www.figma.com/file/FsHxZiRX7HvMtHmxZs5qgV/Untitled

权限喊胧月

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/8476969/168396851-fd5510fe-c36e-48c8-92a6-999244817f15.png">

为了平滑过渡，且逐步完成，不要挤在一期完成全部重构
我们先把核心要弄的上了，楼下逐个模块解析

**Comment by iRuxu** [comment]
## 准备工作
所有代码先写在v2分支上

- [x] 已完成

**Comment by iRuxu** [comment]
## 整体变化
目前首页暂时使用1440居中布局，解决banner适配，首页不好扩展等一系列问题
@iRuxu 

- [x] 已完成

**Comment by iRuxu** [comment]
## 左侧边栏：魔盒助手

@zixuan1986 

components/v2/assistant.vue

1.左上角那里，延续使用现在的daily背景，相关代码照搬，尺寸可能会有调整，先按线上的搬，没用的代码就不要搬了
2.到时候这个下载地址和版本号，我来改，先静态写

<img width="360" alt="image" src="https://user-images.githubusercontent.com/8476969/168396185-308fe115-0f6b-4dfe-ab1e-c54298407684.png">


- [x] 已完成

**Comment by iRuxu** [comment]
## 左侧边栏：新版日历

@Kaviilee 

components/v2/calendar.vue

新版是以当前日为中心，展示前后3天
接口那些不变，主要是前端展示有区别
对应当前日子的小字，是直接在下面展示了

<img width="375" alt="image" src="https://user-images.githubusercontent.com/8476969/168396125-5a67ba6e-7874-472a-9621-9177e52ce78c.png">


- [x] 已完成

**Comment by iRuxu** [comment]
## 左侧其他
@iRuxu 

其余原首页侧边模块：
+ 今日福利：激活码（限时）
+ 官方游戏公告
+ 开服监控
+ 魔盒更新公告
+ 节日活动春节贺卡等（限时特殊）

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧主体
@iRuxu 

+ 特殊直播（限时特殊）

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧头条
@iRuxu 
原来的迁移到v2，迷你图仅鼠标悬浮后展示
尺寸调整为1100*280

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧魔盒矩阵

@iRuxu 
先移植，后续醉栩优化内部逻辑，增加展开相关

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧近期活动
@zixuan1986 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/8476969/168397613-daaae01d-78c9-45aa-9754-ca29b2124d66.png">

components/v2/event.vue

接口读取 `https://cms.jx3box.com/api/cms/news/v2?client=std&type=event&status=1&per=4`
注意请求参数区分正式服与怀旧服
往期活动链接至`/notice?subtype=2`

内容添加地址：
<img width="730" alt="image" src="https://user-images.githubusercontent.com/8476969/168398368-3a66e02a-1e20-4d5b-81e9-dfbea93bec7c.png">

- [x] 已完成

**Comment by iRuxu** [comment]
#### 近期活动具体海报
@胧月
【正式服】
+ 江湖无限PVP征稿活动https://www.jx3box.com/notice/40568
+ 河阳之战天团榜活动 https://www.jx3box.com/notice/306
+ 河阳之战秘境百强榜https://www.jx3box.com/rank/race/#/5  （给个入口，留到下一批活动：团队平台小程序公测再撤）
+ 团队福利申请 https://www.jx3box.com/team/apply/1  （下一批：双端江湖回忆录征稿活动）

【怀旧服】
+ 五毒显示五毒主题征稿活动 https://origin.jx3box.com/notice/40569
+ 荻花圣殿门派天团活动 https://origin.jx3box.com/notice/20
+ 萌新教学团活动 https://origin.jx3box.com/notice/38368
+ 怀旧服任务物品百科完善计划 （下一批：双端江湖回忆录征稿活动）

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧金价
@iRuxu 
先沿用原先的，回头blank接口更新后翻新为新版

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧物价
@iRuxu
先沿用原先的，回头blank接口更新后翻新为新版

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧：最新作品
@zixuan1986 

<img width="707" alt="image" src="https://user-images.githubusercontent.com/8476969/168399327-86faed2a-18e8-48b0-9996-b85b9119b91a.png">

第一个叫最新作品
可以移植现在的index/posts模块，但只包含以下部分：
<img width="728" alt="image" src="https://user-images.githubusercontent.com/8476969/168399388-caada2e7-5acf-444d-8adf-82c7520be05e.png">
重新写到components/v2/post.vue里
移除不要的代码

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧海报
<img width="407" alt="image" src="https://user-images.githubusercontent.com/8476969/168399702-179010fb-f043-466b-8238-75ed75c4cf55.png">

@zixuan1986 

放官方的外观 + 两边新赛季的专题页 + 魔盒核心团队招募 + 魔盒怀旧服内容团队招募，比较常驻类型的

写在 components/v2/banner.vue

要做成slider
接口读取 https://cms.jx3box.com/api/cms/news/v2?client=std&type=banner&status=1&per=4

也是在通用投放里管理

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧：最新百科

在最新作品下面，弄个一样差不多
@zixuan1986 

写在components/v2/wiki.vue

取这个部分的：
<img width="366" alt="image" src="https://user-images.githubusercontent.com/8476969/168399968-10e8bf6b-bdbf-4347-8c84-0545f53869a3.png">


- [x] 已完成

**Comment by iRuxu** [comment]
## 新版首页底部

@zixuan1986 
等胧月给设计稿

主要放我们的二维码矩阵，一些快速通道，等等

- [ ] 已完成

**Comment by iRuxu** [comment]
## 左侧底部
<img width="293" alt="image" src="https://user-images.githubusercontent.com/8476969/168525017-357132e6-2409-4657-9321-e9d834b7e42d.png">

增加新版反馈快捷入口，把茶馆侧边的复制过来，图片得换2倍大小的高清图


@zixuan1986 

- [x] 已完成

**Comment by iRuxu** [comment]
## 日历部分
优化首页日历接口，解决指定条目数返回问题
@Kaviilee 处理

- [ ] 已完成

**Comment by Kaviilee** [comment]
> ## 日历部分
> 接口数量限制无效 @Kaviilee 处理
> 
> * [ ]  已完成

啥意思啊

**Comment by iRuxu** [comment]
## css优化
解决第3方按钮包大量报错
精简仅保留当前按钮样式即可
没时间去筛
@Kaviilee 

- [x] 已完成

**Comment by iRuxu** [comment]
## 日历优化
先有一排灰色是和旧版首页一致显示小字

再有一块是今日的，加个抬头：今日大事件

- [x] 已完成
