### ISSUE TITLE
两处优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#38]
## 数据库版本

现在总是显示当前日期是不合适的
应该显示每个分组下面，最新的那一天日期

- [x] 已完成

**Comment by iRuxu** [comment]
## 最新百科
![image](https://user-images.githubusercontent.com/8476969/193421029-62ccfe90-e5f1-41fe-8b5b-2be7c57985e4.png)

当展示最新任务百科时，这里的 任务 ，其实是有名字的，但是却全部展示成里  无标题，可能是字段取得不对，需要修复

- [ ] 已完成

**Comment by x3zvawq** [comment]
第二个问题 是helper接口的问题
提交攻略的时候后端会在数据库找出那个攻略 然后获取Name 
但是任务库的名称字段是QuestName， 已经修复
但是目前的任务攻略可能title都是空的（不过反正有的也不多
