### ISSUE TITLE
历期头条与公告页优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#61]
## 历期头条
<img width="520" alt="image" src="https://user-images.githubusercontent.com/8476969/216759979-df652ff2-5ad1-4db1-9864-5468c5be8b0d.png">

通过这里链接进入一个页面，可以查看历史的头条的（可以对历史的头条图有曝光），版面上无需考虑现有的，只要有公共头和底即可

- [x] 已完成

**Comment by iRuxu** [comment]
## 公告页
现在的公告页长这样：https://www.jx3box.com/notice/5432
缺乏一定的仪式感

独立设计新版的公告页，可抛弃现有包袱。
只要有公共头和底即可

- [ ] 已完成

**Comment by nierssaxa** [comment]
> ## 历期头条
> <img alt="image" width="520" src="https://user-images.githubusercontent.com/8476969/216759979-df652ff2-5ad1-4db1-9864-5468c5be8b0d.png">
> 
> 通过这里链接进入一个页面，可以查看历史的头条的（可以对历史的头条图有曝光），版面上无需考虑现有的，只要有公共头和底即可
> 
> * [x]  已完成

https://www.figma.com/file/EOlmn8bY6AhCQVSTFgiuu2/JX3BOX-TV?node-id=0%3A1&t=zNmYe8S1nE18icU2-1

**Comment by nierssaxa** [comment]
> ## 公告页
> 现在的公告页长这样：https://www.jx3box.com/notice/5432 缺乏一定的仪式感
> 
> 独立设计新版的公告页，可抛弃现有包袱。 只要有公共头和底即可
> 
> * [x]  已完成

https://www.figma.com/file/cv2XYKO7wgV3QMiymbgaV7/JX3BOX-ANNOUNCEMENT?node-id=1%3A154&t=A38VIJlS4YoUihoR-1
背景图可换，底色可换白色或亮色系

**Comment by iRuxu** [comment]
写在index项目下

历史头条是  /index/tv
公告是现有的 /notice

**Comment by iRuxu** [comment]
接口：https://cms.jx3box.com/api/cms/news/v2?client=std&type=slider&status=1&per=8

**Comment by iRuxu** [comment]
## 历史头条
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/8476969/217937025-3a0f9d74-f50b-41af-bfa8-2e377193475d.png">

需要再优化：
1. 资源筛选，传递source_type，如果全部时不要传递（强校验），可选的列表，请从jx3box.json中读取，全部合一起即可
<img width="358" alt="image" src="https://user-images.githubusercontent.com/8476969/217937206-4a2539a2-1288-44c8-af66-df26f2e04e02.png">

2. 需要处理分页（参数page），可以查看更久远的，不推荐无限滚动，那样无法感知位置，考虑右下角做个简单版的分页（不要搞太多数字，除了显示第一个和最后一个，中间点点点，并且可以自己指定输入）
<img width="593" alt="image" src="https://user-images.githubusercontent.com/8476969/217937556-53829fe4-417d-460e-a76c-a7ca872790c8.png">

具体样式可联系胧月

- [x] 已完成

**Comment by nierssaxa** [comment]
> 

设计稿已更新

**Comment by iRuxu** [comment]
## 历史头条筛选
当前激活状态，使用颜色：#fba524
注意【全部】也要遵循此规则

- [x] 已完成

**Comment by iRuxu** [comment]
![d90cf0eba91441a68826ed5b5352a6eb](https://user-images.githubusercontent.com/8476969/218318920-3635dbee-d564-4e66-b045-59c56afb92f8.png)

点击空白也得让这个消失
可以监听Body然后让它消息，$(document).click，可以看看头部的菜单的做法

- [x] 已完成

**Comment by iRuxu** [comment]
## 历史头条
![d33edf602a7434da62ed9a5b6632210c](https://user-images.githubusercontent.com/8476969/218321299-b457d32d-e0a4-4317-9cbd-fe0cf44648d4.png)

当这里选择后，下面也要跟着改，并且当不是全部时，也要换个高亮颜色

- [x] 已完成

**Comment by iRuxu** [comment]
## 历史头条
另外公告页的背景图乱了，那个你要fixed定位，不要变形。
让背景图 background-size:cover;

- [x] 已完成

**Comment by iRuxu** [comment]
## 历史头条
<img width="478" alt="image" src="https://user-images.githubusercontent.com/8476969/218344096-bf888abc-dd5c-439f-8794-05033ea17b85.png">
适配要做

- [x] 已完成
