### ISSUE TITLE
强制弹窗

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#94]
## 背景介绍
<img width="1739" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/bd2ee354-6dcb-4c66-8f03-9988c251a4e6">

新增了这样一种子类，是为了让用户在进入时，有一些强推广的内容。
目前这里的是专门为pc服务，注意要区分下client参数。
尺寸规范`1000*600`（设计需要做2x图，即`2000*1200`）
其中固定实际内容区域为中间的`1000*500`
而底部的100高度的右侧，默认为一个关闭按钮（怎么花里胡哨的设计随便），前端让底部的100px高度的右侧50%区域点击则执行关闭效果；设计稿可以为不规则图形

<img width="1492" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/5ae59cfa-3f51-49fa-83d8-b8701d9c609d">

- [x] 已完成

**Comment by iRuxu** [comment]
## banner
<img width="425" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/9ed31fa8-b0b4-4ace-ab4b-ad20e502319a">

- [x] 已完成

**Comment by iRuxu** [comment]
## 技改
<img width="404" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/fd2a1dec-1418-4b03-aa08-2f62cfc435e9">

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## 背景介绍
> <img alt="image" width="1739" src="https://user-images.githubusercontent.com/8476969/271351882-bd2ee354-6dcb-4c66-8f03-9988c251a4e6.png">
> 新增了这样一种子类，是为了让用户在进入时，有一些强推广的内容。 目前这里的是专门为pc服务，注意要区分下client参数。 尺寸规范`1000*600`（设计需要做2x图，即`2000*1200`） 其中固定实际内容区域为中间的`1000*500` 而底部的100高度的右侧，默认为一个关闭按钮（怎么花里胡哨的设计随便），前端让底部的100px高度的右侧50%区域点击则执行关闭效果；设计稿可以为不规则图形
> 
> <img alt="image" width="1492" src="https://user-images.githubusercontent.com/8476969/271353416-5ae59cfa-3f51-49fa-83d8-b8701d9c609d.png">
> * [x]  已完成

在dev分支

**Comment by iRuxu** [comment]
<img width="999" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/06e89109-cd4b-463a-a97b-e317b7410e45">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1395" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/bf4f610c-24b7-4677-9a8d-ee89f31f7e65">
再次调整！

- [x] 已完成
