### ISSUE TITLE
首次引导

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#95]
## 触发逻辑
当用户首次进入魔盒时（在localstorage记录一个标记）
同时服务器端也用user/meta接口标记一下
key使用`new_user_guide`

如果本地有标记了，不再弹出对应逻辑
如果本地没有，但请求服务器如果是有标记的（在其他电脑用过），则也不弹了，并且在本地标记一下。，

- [x] 已完成

**Comment by iRuxu** [comment]
## 引导路线

1. 左上角切换客户端（文案`可以在此处全局切换正式服（重制版）和怀旧服（缘起）喔~`）
2. 右上角个人中心（文案`资料修改、福利兑换等在这里喔~`）
3. 导航（文案`主要栏目可以在这里切换喔~`）
4. 矩阵（文案`常用的应用可以在这里快速跳转，支持自定义喔~`）


自己找个轮子，框个大概的区域就可以

- [x] 已完成

**Comment by Kaviilee** [comment]
在dev分支

**Comment by iRuxu** [comment]
dev分支测试未触发对应逻辑，请检查

**Comment by Kaviilee** [comment]
> dev分支测试未触发对应逻辑，请检查

需要安装依赖
