### ISSUE TITLE
名望拓展

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/index_v1#99]
## 后台
在编辑部，新增【活动配置】组，并新增【名望配置】
路由 ： /editor/event/celebrity

一套标准的CURD
路由权限：manage_activity_celebrity

<img width="1067" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/bce9f5f1-be17-4848-9694-c270a6d90494">

type需要自己定义 一个作为楚天社，一个作为新的名称。
可以用拼音。

数据需要自己录入
[云从社.txt](https://github.com/JX3BOX/index/files/12908869/default.txt)

- [x] 已完成

**Comment by iRuxu** [comment]
## 资源

[minimap.zip](https://github.com/JX3BOX/index/files/12907032/minimap.zip)

涉及的一些图标，其余需要的找南宫伯


- [x] 已完成

**Comment by iRuxu** [comment]
## index
<img width="424" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/2b18922e-ea82-4cce-9ea8-0e4311037b0b">

- [x] 已完成

**Comment by iRuxu** [comment]
## pvx
<img width="1798" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/40e6cc22-96da-4ce4-8cc1-710a6f816a26">

- [ ] 已完成

**Comment by fifthThirteen** [comment]
后台是否是录入还是直接放到数据库的具体不太清楚，前端请求楚天社名望数据的接口是这个。
https://node.jx3box.com/celebrities?client=std

楚天社是一个循环由4个地图共分2个小时，引入了一个key的概念来判断属于哪个地图和哪个时间段。
云从社是一个地图（银霜口）2个小时一个循环，可以不用key。

如果放入一个表的话就要加个整体type来区分是楚天社还是云从社或者说是以后新赛季的其他社了。

不过不清楚新赛季楚天社是否会停止或者玩家如果能通过云从社获取楚天社的声望之类的，这样的话楚天社都可以去掉了。

所以个人建议还是先做个单独的表？

**Comment by iRuxu** [comment]
## 作品管理
<img width="1911" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/6715dc77-0139-485c-b334-77f15a799ca9">

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="1502" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/acf98381-7d8a-4d02-be14-3b8a000aded6">

排行榜这里顺序有点问题

- [ ] 已完成

**Comment by iRuxu** [comment]
## 作品管理
<img width="1918" alt="image" src="https://github.com/JX3BOX/index/assets/8476969/f27cb2c1-da92-4177-9bf4-c8f714830718">
可以做成slot吧。
默认没有app就保留现在的，有app的时候，就支持加载slot进来的

- [ ] 已完成
